# PyTorch Fundamentals

## Importing and Verifying Cuda:

In [1]:
import torch

torch.set_printoptions(linewidth=200)

print(f"Version: {torch.__version__}")

Version: 2.11.0+cu130


In [2]:
torch.cuda.is_available()

True

In [100]:
torch.cuda.device_count()

1

## torch.tensor() Class:

### Creating device:

In [3]:
cuda = torch.device('cuda')

print(cuda)

cuda


### Scalar:

In [4]:
scalar = torch.tensor(1)

print(f"Scalar: {scalar}")
print(f"Type: {type(scalar)}")
print(f"num dims: {scalar.ndim}")

Scalar: 1
Type: <class 'torch.Tensor'>
num dims: 0


In [5]:
item = scalar.item()

print(f"item: {item}")
print(f"Type: {type(item)}")

item: 1
Type: <class 'int'>


### Vector:

In [6]:
vector = torch.tensor([1])

print(f"Vector: {vector}")
print(f"Type: {type(vector)}")
print(f"Num dims: {vector.ndim}")

Vector: tensor([1])
Type: <class 'torch.Tensor'>
Num dims: 1


### Ones and Zeros:

In [7]:
torch.ones([2, 4], dtype = torch.float64, device = cuda, requires_grad = False)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], device='cuda:0', dtype=torch.float64)

In [8]:
x = torch.zeros([10])
print(f"X elements' type: {x.dtype}")

X elements' type: torch.float32


In [9]:
print(x[2])

tensor(0.)


In [10]:
x[3] = 8

print(f"X: {x}")
print(f"X shape: {x.shape}")

X: tensor([0., 0., 0., 8., 0., 0., 0., 0., 0., 0.])
X shape: torch.Size([10])


### Higher dimensional Tensor:

In [11]:
x1 = torch.tensor([[2, 4], [1, 3], [1, 1]])
print(x1)
print(x1.dtype)
print(x1.device)
print(x1.ndim)
print(x1.shape)

tensor([[2, 4],
        [1, 3],
        [1, 1]])
torch.int64
cpu
2
torch.Size([3, 2])


In [12]:
x1 = x1.to(cuda)
print(x1)
print(x1.dtype)
print(x1.device)
print(x1.ndim)
print(x1.shape)

tensor([[2, 4],
        [1, 3],
        [1, 1]], device='cuda:0')
torch.int64
cuda:0
2
torch.Size([3, 2])


In [13]:
x2 = torch.tensor([[
                    [2, 1, 4], 
                    [2.2, 1, 5], 
                    [1e-2, 0 , 0]
                    ], 
                   [
                    [2, 1, 4], 
                    [2.2, 1, 5], 
                    [10e-2, 0 , 0]
                    ]
                    ])
print(x2)
print(x2.dtype)
print(x2.device)
print(x2.ndim)
print(x2.shape)

tensor([[[2.0000, 1.0000, 4.0000],
         [2.2000, 1.0000, 5.0000],
         [0.0100, 0.0000, 0.0000]],

        [[2.0000, 1.0000, 4.0000],
         [2.2000, 1.0000, 5.0000],
         [0.1000, 0.0000, 0.0000]]])
torch.float32
cpu
3
torch.Size([2, 3, 3])


### Random Tensors:

In [14]:
random_tensor = torch.rand([10, 2])

print(f"Random tensor:\n\n{random_tensor}\n")
print(f"Shape: {random_tensor.shape}")
print(f"N dims: {random_tensor.ndim}")

Random tensor:

tensor([[0.0850, 0.7282],
        [0.0333, 0.2605],
        [0.8659, 0.5899],
        [0.1516, 0.9358],
        [0.6253, 0.8957],
        [0.8254, 0.8413],
        [0.0593, 0.2496],
        [0.3831, 0.5123],
        [0.5189, 0.4486],
        [0.6011, 0.4915]])

Shape: torch.Size([10, 2])
N dims: 2


### Crating tensors with a range:

In [15]:
ranged_0_9 = torch.arange(start = 0, end = 10, step = 1)

print(f"Ranged vector: {ranged_0_9}")

Ranged vector: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [16]:
ranged_0_9 = torch.arange(0, 10)

print(f"Ranged vector: {ranged_0_9}")

Ranged vector: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


### Zeros and Ones Like Tensor:    

In [17]:
x = torch.rand([2, 10])

print(f"X: \n\n{x}\n")
print(f"Shape: {x.shape}")

x0 = torch.zeros_like(x)

print(f"X0: \n\n{x0}\n")
print(f"Shape: {x0.shape}")

x1 = torch.ones_like(x)

print(f"X1: \n\n{x1}\n")
print(f"Shape: {x1.shape}")



X: 

tensor([[0.1964, 0.2210, 0.4221, 0.8947, 0.8465, 0.6698, 0.4992, 0.3525, 0.5836, 0.2800],
        [0.6214, 0.0828, 0.1833, 0.1880, 0.3819, 0.2036, 0.0043, 0.2812, 0.1417, 0.9757]])

Shape: torch.Size([2, 10])
X0: 

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

Shape: torch.Size([2, 10])
X1: 

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

Shape: torch.Size([2, 10])


## Tensor Operations:

### Addition, Subtraction, Multiplication (element-wise): 

In [18]:
t1 = torch.tensor([1, 2, 3])
t2 = torch.tensor([3, 2, 1])

In [19]:
print(t1+2)

tensor([3, 4, 5])


In [20]:
print(t1+t2)

tensor([4, 4, 4])


In [21]:
print(t1-t2)

tensor([-2,  0,  2])


In [22]:
print(t1*10)
print(t2*7)

tensor([10, 20, 30])
tensor([21, 14,  7])


In [23]:
print(t1*t2)

tensor([3, 4, 3])


### Dot Product and Matrix Multiplication

In [24]:
t1.dot(t2)

tensor(10)

In [25]:
t2.dot(t1)

tensor(10)

In [ ]:
t1 = torch.tensor([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

t2 = t1.clone()

t2 = t2 + 10

In [83]:
print(t1[:, :])
print(t1[:, 0])
print(t1[0, :])
print(t1[0, 0])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([1, 4, 7])
tensor([1, 2, 3])
tensor(1)


In [27]:
print(t1)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [28]:
print(t2)

tensor([[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]])


In [29]:
print(t1 @ t2)
print()
print(torch.matmul(t1, t2))

tensor([[ 90,  96, 102],
        [216, 231, 246],
        [342, 366, 390]])

tensor([[ 90,  96, 102],
        [216, 231, 246],
        [342, 366, 390]])


In [30]:
print(t2 @ t1)
print()
print(torch.matmul(t2, t1))

tensor([[150, 186, 222],
        [186, 231, 276],
        [222, 276, 330]])

tensor([[150, 186, 222],
        [186, 231, 276],
        [222, 276, 330]])


### Transpose:

In [31]:
print(t1)
print()
print(t1.T)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])


### Linear Layer:

$$y = x W^{T} + b$$

In [32]:
torch.manual_seed(42)

linear = torch.nn.Linear(in_features=3, out_features=10, device=cuda, dtype=torch.float64)

# Since the matrix in the Linear layer is transposed, the in_features actually represent the number of columns of the input tensor.

# W has shape (out_features, in_features)

x = torch.tensor([
    [1, 2, 3],
    [3, 4, 55],
], device=cuda, dtype=torch.float64)

output = linear(x)

In [33]:
print(f"Input shape: {x.shape}\n")
print(f"Output:\n\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([2, 3])

Output:

tensor([[ -1.0290,   0.7489,   0.0689,   0.7179,  -0.3755,  -0.7902,  -1.5974,  -0.5829,  -1.0526,   1.1450],
        [ -0.7495,  -4.2785, -24.1016,   9.7831,  19.4860, -26.3588, -27.1520, -21.8386, -18.0783,  11.6218]], device='cuda:0', dtype=torch.float64, grad_fn=<AddmmBackward0>)

Output shape: torch.Size([2, 10])


### Utils:

In [34]:
print(x.max())
print(x.min())
print(x.mean())
print(x.sum())

tensor(55., device='cuda:0', dtype=torch.float64)
tensor(1., device='cuda:0', dtype=torch.float64)
tensor(11.3333, device='cuda:0', dtype=torch.float64)
tensor(68., device='cuda:0', dtype=torch.float64)


In [35]:
print(x.argmax())

tensor(5, device='cuda:0')


In [36]:
print(x.argmin())

tensor(0, device='cuda:0')


### Reshaping, Stacking, Squeezing & Unsqueezing:

In [43]:
x = torch.arange(0, 8, dtype=torch.float32)
print(x)
print(x.shape)

tensor([0., 1., 2., 3., 4., 5., 6., 7.])
torch.Size([8])


In [49]:
# copy the data

x_reshaped = x.reshape(2, 4)
print(x_reshaped)
print(x_reshaped.shape)

tensor([[0., 1., 2., 3.],
        [4., 5., 6., 7.]])
torch.Size([2, 4])


In [48]:
# share the same memory, need to be continuous

z = x.view(2, 4)
print(z)
print(z.shape)

tensor([[0., 1., 2., 3.],
        [4., 5., 6., 7.]])
torch.Size([2, 4])


In [56]:
x_stacked = torch.stack([x, x, x], dim = 0)
x_stacked

tensor([[0., 1., 2., 3., 4., 5., 6., 7.],
        [0., 1., 2., 3., 4., 5., 6., 7.],
        [0., 1., 2., 3., 4., 5., 6., 7.]])

In [57]:
x_stacked = torch.stack([x, x, x], dim = 1)
x_stacked

tensor([[0., 0., 0.],
        [1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.],
        [4., 4., 4.],
        [5., 5., 5.],
        [6., 6., 6.],
        [7., 7., 7.]])

In [67]:
x = x.reshape(1, 8)
x_squeezed = torch.squeeze(x)

x_unsqueezed = x_squeezed.unsqueeze(dim = 0)

print(f"{x} : {x.shape}")

print(f"{x_squeezed}   : {x_squeezed.shape}")

print(f"{x_unsqueezed} : {x_unsqueezed.shape}")

tensor([[0., 1., 2., 3., 4., 5., 6., 7.]]) : torch.Size([1, 8])
tensor([0., 1., 2., 3., 4., 5., 6., 7.])   : torch.Size([8])
tensor([[0., 1., 2., 3., 4., 5., 6., 7.]]) : torch.Size([1, 8])


In [70]:
# It is a view of the original -> if you change, the original also gets changed

x_original = torch.rand(size=(224,224,3))

x_permuted = x_original.permute(2, 0, 1)

print(x_original.shape)

print(x_permuted.shape)

torch.Size([224, 224, 3])
torch.Size([3, 224, 224])


## PyTorch & Numpy:

In [88]:
import numpy as np

array = np.arange(1.0, 8.0)
array, type(array)

(array([1., 2., 3., 4., 5., 6., 7.]), numpy.ndarray)

In [96]:
tensor = torch.from_numpy(array)
tensor, type(tensor)

(tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64), torch.Tensor)

In [97]:
new_array = tensor.numpy()
new_array, type(new_array)

(array([1., 2., 3., 4., 5., 6., 7.]), numpy.ndarray)

## Reproducibility:

In [99]:
torch.manual_seed(42)

https://docs.pytorch.org/docs/2.11/notes/randomness.html

# Exercise:

In [115]:
device = "cuda" if torch.cuda.is_available else "cpu"

print(f"device: {device}")

torch.cuda.manual_seed(42)

x = torch.rand(7, 7, device=device)

print(f"X: {x}, {x.shape}")

y = torch.rand(1, 7, device=device)

print(f"Y: {y}, {y.shape}")

device: cuda
X: tensor([[0.6130, 0.0101, 0.3984, 0.0403, 0.1563, 0.4825, 0.7362],
        [0.4060, 0.5189, 0.2867, 0.2416, 0.9228, 0.8299, 0.0342],
        [0.3879, 0.0824, 0.7742, 0.2792, 0.5138, 0.2068, 0.0074],
        [0.8750, 0.9682, 0.1201, 0.1972, 0.4503, 0.0511, 0.4892],
        [0.9331, 0.3807, 0.0509, 0.2663, 0.6495, 0.2675, 0.1733],
        [0.8565, 0.2761, 0.2093, 0.0711, 0.7701, 0.6100, 0.3444],
        [0.9852, 0.4692, 0.9203, 0.7127, 0.1052, 0.8138, 0.1092]], device='cuda:0'), torch.Size([7, 7])
Y: tensor([[0.9877, 0.1289, 0.5621, 0.5221, 0.7445, 0.5955, 0.9647]], device='cuda:0'), torch.Size([1, 7])


In [119]:
z = x @ y.T
print(z)

tensor([[1.9656],
        [1.9694],
        [1.4875],
        [1.9972],
        [1.9483],
        [2.3051],
        [2.5913]], device='cuda:0')


In [120]:
print(z.max())
print(z.min())

tensor(2.5913, device='cuda:0')
tensor(1.4875, device='cuda:0')


In [121]:
print(z.argmax())
print(z.argmin())

tensor(6, device='cuda:0')
tensor(2, device='cuda:0')


In [133]:
torch.manual_seed(42)

a = torch.rand(1, 1, 1, 10)

b = a.squeeze()

print(f"A: {a}, {a.shape}")
print(f"B: {b}, {b.shape}")

A: tensor([[[[0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009, 0.2566, 0.7936, 0.9408, 0.1332]]]]), torch.Size([1, 1, 1, 10])
B: tensor([0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009, 0.2566, 0.7936, 0.9408, 0.1332]), torch.Size([10])
